name: Terraform CI/CD

on:
  push:
    branches:
      - '*'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_SP_CLIENTID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_SP_PASSWORD }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Terraform Init
      run: | 
        terraform init
        terraform validate
      working-directory: Infra
        
  validate-Vue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: npm ci

    - name: Run Vue Lint
      run: npm run lint

    - name: Run Vue Tests
      run: npm run test

  apply:
    if: github.ref == 'refs/heads/main'
    needs: [validate-terraform, validate-Vue]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6
    
    - name: Terraform Init
      run: | 
        terraform init
        terraform apply -auto-approve
      working-directory: Infra
